### ISSUE TITLE
Missing return in RegistryAdmin Import function causing an error on successful import

### ISSUE THREAD

**Issue by CCCMichaelCole** [silverstripe/silverstripe-registry#113]
### Module version(s) affected

3.2.0

### Description

When importing a CSV file into a registry it will **complete** the import but fails to return (redirect) back to the registry popup dialog with a **"good"** (successful) message. The user's gets a broken screen (css not loading). Everything else works as expected.

### How to reproduce

1. Go to Registry (Admin) > select a registry model and Export to CSV.
2. Import CSV back into registry model and it will fail to display the successful message.

**Error**
[Emergency] Uncaught TypeError: SilverStripe\Registry\RegistryAdmin::import(): **Return value must be of type SilverStripe\Control\HTTPResponse, none returned**

### Possible Solution

Edit RegistryAdmin.php and add **return** to line 126 - import function

**Currently**
$this->redirectBack();
**Fix** 
return $this->redirectBack(); 

### Additional Context

I will do a pull request from my fork. This isn't a showstopper as everything actually works, but we have several business units importing their own registries, and it would be nice to get this sorted before we go live with CMS 5.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub Actions.
Thanks for the work
