### ISSUE TITLE
Summary definition throws an error if value doesn't exist

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-registry#44]
It appears that an assumption is made that all values in `summary_fields` exist. I tried to build a registry and one of the values - an image source - did not exist. 
This caused a database exception, where the search query could not be run due to the non-existing field.

**Comment by NightJar** [comment]
Addendum: That all defined fields exist _in the database_ (ie. as `$db` fields, or at least exist in a manner that the ORM can deal with). This leaves the likes of:

```
getThumbnail()
{
    // ...
    return $Image->CMSThumbnail();
}
```

Which is an absolutely valid and not so uncommon approach to a `summary_field` cause the error as mentioned, due to ` SELECT "getThumbnail" , ...` giving an expected error of no such field existing.

**Comment by be2n** [comment]
@NightJar following your addendum, would should this issue still be considered a bug?

**Comment by dhensby** [comment]
@be2n The lable `type/bug` is still applied, so I don't think anyone's suggesting it's no longer a bug

**Comment by NightJar** [comment]
@be2n Yes; my earlier comment is merely an expansion of explanation ;)

**Comment by robbieaverill** [comment]
FYI the code that does this is `RegistryPageController::queryList`:

```php
$resultColumns = $this->dataRecord->getDataSingleton()->summaryFields();
$resultColumns['ID'] = 'ID';
$results = ArrayList::create();

$query = SQLSelect::create();
$query
    ->setSelect($this->escapeSelect(array_keys($resultColumns)))
    ->setFrom('"' . $tableName . '"');
$query->addWhere($where);
$query->addOrderBy($orderby);
$query->setConnective('AND');
```

**Comment by robbieaverill** [comment]
We could either try and remove this logic and try and make it work the same way as core does for summary fields, or we could do a pass before the DB query to resolve any PHP methods then remove them from the list before the query is created
